import { AlertTriangle, Boxes, Euro, PackageX } from 'lucide-react'
import type { Movement, Product } from '../types'
const money = new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR',maximumFractionDigits:0})
export default function Dashboard({products,movements}:{products:Product[];movements:Movement[]}){
  const low=products.filter(p=>p.stock>0&&p.stock<=p.threshold)
  const empty=products.filter(p=>p.stock===0)
  const totalValue=products.reduce((sum,p)=>sum+(p.purchasePrice??0)*p.stock,0)
  return <section><header><p className="eyebrow">Vue d'ensemble</p><h1>Tableau de bord</h1><p className="page-intro">L’essentiel du stock, visible en un coup d’œil.</p></header><div className="hero-stats"><article className="hero-stat products-stat"><div className="stat-icon"><Boxes/></div><span>Produits</span><b>{products.length}</b></article><article className="hero-stat low-stat"><div className="stat-icon"><AlertTriangle/></div><span>Stock faible</span><b>{low.length}</b></article><article className="hero-stat empty-stat"><div className="stat-icon"><PackageX/></div><span>Ruptures</span><b>{empty.length}</b></article><article className="hero-stat value-stat"><div className="stat-icon"><Euro/></div><span>Valeur du stock</span><b>{money.format(totalValue)}</b></article></div><div className="cols"><div className="panel"><h2>À surveiller</h2>{[...empty,...low].length===0?<p>Aucune alerte. Tout est au vert.</p>:[...empty,...low].map(p=><div className="row" key={p.id}><div><b>{p.name}</b><small>{p.cultures.join(', ')}</small></div><strong className={p.stock===0?'bad':'warning-text'}>{p.stock} {p.unit}</strong></div>)}</div><div className="panel"><h2>Derniers mouvements</h2>{movements.length===0?<p>Aucun mouvement.</p>:movements.slice(0,6).map(m=>{const p=products.find(x=>x.id===m.productId);return <div className="row" key={m.id}><div><b>{p?.name||'Produit supprimé'}</b><small>{new Date(m.date).toLocaleString('fr-FR')} · {m.reason||'Mouvement'}</small></div><strong className={m.type==='entry'?'ok':''}>{m.type==='entry'?'+':'-'}{m.quantity} {p?.unit}</strong></div>})}</div></div></section>
}
